### ISSUE TITLE
Add support for padding reporting

### ISSUE THREAD

**Issue by louiscryan** [python-hyper/draft-http2-debug-state#1]
Padding counts against flow-control window and should be accounted for. 

Currently spec has dataIn / dataOut which does not include padding. We've seen issues with padding arithmetic omissions causing flow-control drift.

https://github.com/netty/netty/issues/5434

Add paddingIn / out per stream?

**Comment by Lukasa** [comment]
Seems reasonable enough to me. @bradfitz does the Golang implementation of this include padding data in dataIn/dataOut?

**Comment by bradfitz** [comment]
Sounds good to me. My current implementation does not include padding in the `dataIn` number. I actually suspect Go's implementation is wrong here with respect to flow control, now that @louiscryan mentions it. I'll double-check.

We never generate padding out, so that field is easy to compute.

**Comment by Lukasa** [comment]
Yeah, the same is true with the Python implementation (re: generating padding out). I feel more confident that we're getting the arithmetic right though.

Ok, cool, let's add this too.

**Comment by Lukasa** [comment]
Added in master.
