### ISSUE TITLE
Add support for Stream creation Timestamps

### ISSUE THREAD

**Issue by carl-mastrangelo** [python-hyper/draft-http2-debug-state#4]
A useful measure of why streams are slow is the timestamp at which a stream ID is allocated.  Consider the following setup:

Client ----> Proxy ----> Server

When the client creates a stream  to the proxy, the proxy may be overloaded, or not have the ability to create it due to max concurrent streams already being full.  When inquiring as to why a request took a long time, it would be useful to know when the Proxy actually allocated the outbound stream.

This would also have the benefit that, knowing the total number of bytes sent on the stream, it would be possible to measure the bandwidth of the stream.  Assuming clocks are in relative sync, it would be possible to measure (as a third party, separate from each of the endpoints above) the total bandwidth of a stream.

**Comment by Lukasa** [comment]
Yup, this seems like a sensible optional field.

**Comment by Lukasa** [comment]
Now in the current working copy.
